on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  packages: write
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: '@vuemark/core'

      - uses: actions/checkout@v4
        name: Checkout
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v1
        name: Setup Node.js
        with:
          node-version: 20
          scope: '@vuemark'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
        if: ${{ steps.release.outputs.release_created }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: pnpm i --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}

      - name: Build package
        run: pnpm build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to GitHub Packages
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}